import './globals.css'
import { Inter } from 'next/font/google'
import HEADER from './components/header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font-mono'>
      <body className={inter.className}>
      <HEADER></HEADER>
        {children}
        </body>
    </html>
  )
}
